version: '3.9'

services:

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shop
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./:/workspace
    working_dir: /workspace
    ports:
      - 5432:5432
volumes:
  postgres: